### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This is a small PR that adds two links to get your app on Google Play and F-Droid 👍

### CODE REVIEW

**Comment by meolunr** [comment]
I am sorry. I don't merge this PR because the Themeify IconPack on Google Play is not uploaded by myself, it even modified original designer.

**Comment by Poussinou** [comment]
Hum, I didn't know the google play package wasn't from you... Do you mean this developer is just a robber?

If it's the case, you can report him here I think: https://support.google.com/legal/contact/lr_dmca?product=googleplay

Anyway, I removed the link to Google Play ;)

**Comment by Poussinou** [comment]
Is this another copy of your app? https://play.google.com/store/apps/details?id=pixeify.icon.pack

**Comment by meolunr** [comment]
Yes, that developer is just a robber. 
Both Themeify and Pixeify IconPack on Google Play are copied from my repository. I have reported to Google Play and am waiting for a reply.

In addition, I have merged this PR, thank you for your help!

**Comment by Poussinou** [comment]
Tell me when you got the answer, just for my personal curiosity :)

**Comment by meolunr** [comment]
Until now, Google Play has not replied to me yet. :worried:

**Pull request merged**
